# Generated by Django 5.0.4 on 2024-04-18 17:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_alter_blogpost_author'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Author',
        ),
    ]
